[book]
language = "en"
multilingual = false
src = "src"
title = "Central Command"
description = ""

[output.html]
git-repository-url = "https://github.com/Central-Command/Wiki"
edit-url-template = "https://github.com/Central-Command/Wiki/edit/main/src/{path}"
site-url = "/Wiki/"